src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("user:read")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups("user:read")
     */
    private $email;
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("user:read")
     */
    private $firstname;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;
    private $plainPassword;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="owner")
     */
    private $questions;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }
    public function getplainPassword(): ?string
    {
        return $this->plainPassword;
    }
    public function setplainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }
    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }
    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }
    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @Groups("user:read")
     */
    public function getAvatarUri(int $size = 32): string
    {
        return 'https://ui-avatars.com/api/?' . http_build_query([
            'name' => $this->getDisplayName(),
            'size' => $size,
            'background' => 'random',
        ]);
    }
    public function getDisplayName(): string
    {
        return $this->getFirstName() ?: $this->getEmail();
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setOwner($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getOwner() === $this) {
                $question->setOwner(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@1&display=swap" rel="stylesheet">
            
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body 
        {% if is_granted('IS_AUTHENTICATED_REMEBERED') %}
            {{ stimulus_controller('user-api', {
                url: path('app_user_api_me')
            }) }}
        {% endif %}
    >
    <nav class="navbar navbar-expand-sm navbar-light" id="neubar">
     <div class="container">
        <a class="navbar-brand" style="font-family: 'DM Serif Display', serif;"  href="{{ path('app_acc') }}">SYMFORUM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class=" collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto ">
        <li class="nav-item">
          <a class="nav-link mx-2 active" aria-current="page" href="{{ path('app_home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{{ path('app_popular_answers') }}">Answers</a>
        </li>
        
            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item">
                    <a class="nav-link mx-2" href="{{ path('admin_dashboard') }}">SERVICE ADMIN</a>
                </li>
            {% endif %}
            
        {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}

            <li class="nav-item dropdown">
            <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img
                                    src="{{ app.user.avatarUri }}"
                                    alt="{{ app.user.displayName }} Avatar">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% if is_granted('ROLE_PREVIOUS_ADMIN') %}
                                    <li>
                                        <a class="dropdown-item" href="{{ path('app_home', {
                                            '_switch_user': '_exit'
                                        }) }}">Exit Impersonation</a>
                                    </li>
                {% endif %}
                <li><a class="dropdown-item" href="{{ path('app_logout') }}">LOGOUT</a></li>
            </ul>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link mx-2" href="{{ path('app_login') }}">LOGIN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link mx-2" href="{{ path('app_register') }}">SIGN UP</a>
            </li>  
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

    
        {# 

                    </ul> #}
                    {# {% if  is_granted('IS_AUTHENTICATED_REMEMBERED')%}
                        {# first method #}
                        {# <div style="margin-right:25px">Hi <i style="color: red;" class="fa fa-heart"></i> {{ app.user.firstname }} !</div>
                        <a href="{{ path('app_logout') }}" class="btn btn-dark">LOGOUT</a> #}

                         {# <div class="dropdown">
                            <button
                                class="dropdown-toggle btn"
                                type="button"
                                id="user-dropdown"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                 <img
                                    src="{{ app.user.avatarUri }}"
                                    alt="{{ app.user.displayName }} Avatar">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="user-dropdown">
                                {% if is_granted('ROLE_PREVIOUS_ADMIN') %}
                                    <li>
                                        <a class="dropdown-item" href="{{ path('app_homepage', {
                                            '_switch_user': '_exit'
                                        }) }}">Exit Impersonation</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a class="dropdown-item" href="{{ path('app_logout') }}">Log Out</a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <a href="{{ path('app_login') }}" class="btn btn-dark" style="margin-right:15px;" >LOGIN</a>
                        <a href="{{ path('app_register') }}" class="btn btn-dark" >Register</a>
                    {% endif %}
                </div>
            </div>
        </nav> #}

        {% block body %}{% endblock %}
            <style>
            #neubar {
            background-color: #DAE2F8;
            color:white;
            }
            #neubar .dropdown-menu a:hover {
            color: #454545;
            }
            #neubar .nav-item {
            margin : auto 4px;
            }
            #neubar a {

            padding-left:12px;
            padding-right:12px;
            }
            #neubar .dropdown-menu {
            background : #DAE2F8
            }
            a.navbar-brand {
            color: #454545
            }
                #footer {
                background: #DAE2F8;
                padding: 30px 0;
                color: black;
                font-size: 14px;
                position: relative;
                }
                #footer .copyright {
                text-align: center;
                }
                #footer .credits {
                padding-top: 10px;
                text-align: center;
                font-size: 13px;
                color: black;
                }
                #footer .credits a {
                color: #4A569D;
                text-decoration:none;
                }
            </style>
        

        <!-- ======= Footer ======= -->
        <footer id="footer">
            <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>SYMFONY FORUM</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Designed by <a href="">Mohamed Sghir</a>
            </div>
            </div>
        </footer><!-- End #footer -->
    
    </body>
</html>